package gg.archipelago.aprandomizer.locations;

import gg.archipelago.aprandomizer.APRandomizer;
import gg.archipelago.aprandomizer.APRegistries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;

public class APLocations {
    
    public static final ResourceKey<APLocation> VANILLA_NETHER_OBTAIN_CRYING_OBSIDIAN = id("vanilla/nether/obtain_crying_obsidian");
    public static final ResourceKey<APLocation> VANILLA_NETHER_DISTRACT_PIGLIN = id("vanilla/nether/distract_piglin");
    public static final ResourceKey<APLocation> VANILLA_STORY_OBTAIN_ARMOR = id("vanilla/story/obtain_armor");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_VERY_VERY_FRIGHTENING = id("vanilla/adventure/very_very_frightening");
    public static final ResourceKey<APLocation> VANILLA_STORY_LAVA_BUCKET = id("vanilla/story/lava_bucket");
    public static final ResourceKey<APLocation> VANILLA_END_KILL_DRAGON = id("vanilla/end/kill_dragon");
    public static final ResourceKey<APLocation> VANILLA_NETHER_ALL_POTIONS = id("vanilla/nether/all_potions");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_TAME_AN_ANIMAL = id("vanilla/husbandry/tame_an_animal");
    public static final ResourceKey<APLocation> VANILLA_NETHER_CREATE_BEACON = id("vanilla/nether/create_beacon");
    public static final ResourceKey<APLocation> VANILLA_STORY_DEFLECT_ARROW = id("vanilla/story/deflect_arrow");
    public static final ResourceKey<APLocation> VANILLA_STORY_IRON_TOOLS = id("vanilla/story/iron_tools");
    public static final ResourceKey<APLocation> VANILLA_NETHER_BREW_POTION = id("vanilla/nether/brew_potion");
    public static final ResourceKey<APLocation> VANILLA_END_DRAGON_EGG = id("vanilla/end/dragon_egg");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_FISHY_BUSINESS = id("vanilla/husbandry/fishy_business");
    public static final ResourceKey<APLocation> VANILLA_NETHER_EXPLORE_NETHER = id("vanilla/nether/explore_nether");
    public static final ResourceKey<APLocation> VANILLA_NETHER_RIDE_STRIDER = id("vanilla/nether/ride_strider");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SNIPER_DUEL = id("vanilla/adventure/sniper_duel");
    public static final ResourceKey<APLocation> VANILLA_NETHER_ROOT = id("vanilla/nether/root");
    public static final ResourceKey<APLocation> VANILLA_END_LEVITATE = id("vanilla/end/levitate");
    public static final ResourceKey<APLocation> VANILLA_NETHER_ALL_EFFECTS = id("vanilla/nether/all_effects");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_BULLSEYE = id("vanilla/adventure/bullseye");
    public static final ResourceKey<APLocation> VANILLA_NETHER_GET_WITHER_SKULL = id("vanilla/nether/get_wither_skull");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_BRED_ALL_ANIMALS = id("vanilla/husbandry/bred_all_animals");
    public static final ResourceKey<APLocation> VANILLA_STORY_MINE_STONE = id("vanilla/story/mine_stone");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_TWO_BIRDS_ONE_ARROW = id("vanilla/adventure/two_birds_one_arrow");
    public static final ResourceKey<APLocation> VANILLA_STORY_ENTER_THE_NETHER = id("vanilla/story/enter_the_nether");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_WHOS_THE_PILLAGER_NOW = id("vanilla/adventure/whos_the_pillager_now");
    public static final ResourceKey<APLocation> VANILLA_STORY_UPGRADE_TOOLS = id("vanilla/story/upgrade_tools");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_TACTICAL_FISHING = id("vanilla/husbandry/tactical_fishing");
    public static final ResourceKey<APLocation> VANILLA_STORY_CURE_ZOMBIE_VILLAGER = id("vanilla/story/cure_zombie_villager");
    public static final ResourceKey<APLocation> VANILLA_END_FIND_END_CITY = id("vanilla/end/find_end_city");
    public static final ResourceKey<APLocation> VANILLA_STORY_FORM_OBSIDIAN = id("vanilla/story/form_obsidian");
    public static final ResourceKey<APLocation> VANILLA_END_ENTER_END_GATEWAY = id("vanilla/end/enter_end_gateway");
    public static final ResourceKey<APLocation> VANILLA_NETHER_OBTAIN_BLAZE_ROD = id("vanilla/nether/obtain_blaze_rod");
    public static final ResourceKey<APLocation> VANILLA_NETHER_LOOT_BASTION = id("vanilla/nether/loot_bastion");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SHOOT_ARROW = id("vanilla/adventure/shoot_arrow");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_SILK_TOUCH_NEST = id("vanilla/husbandry/silk_touch_nest");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_ARBALISTIC = id("vanilla/adventure/arbalistic");
    public static final ResourceKey<APLocation> VANILLA_END_RESPAWN_DRAGON = id("vanilla/end/respawn_dragon");
    public static final ResourceKey<APLocation> VANILLA_STORY_SMELT_IRON = id("vanilla/story/smelt_iron");
    public static final ResourceKey<APLocation> VANILLA_NETHER_CHARGE_RESPAWN_ANCHOR = id("vanilla/nether/charge_respawn_anchor");
    public static final ResourceKey<APLocation> VANILLA_STORY_SHINY_GEAR = id("vanilla/story/shiny_gear");
    public static final ResourceKey<APLocation> VANILLA_END_ELYTRA = id("vanilla/end/elytra");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SUMMON_IRON_GOLEM = id("vanilla/adventure/summon_iron_golem");
    public static final ResourceKey<APLocation> VANILLA_NETHER_RETURN_TO_SENDER = id("vanilla/nether/return_to_sender");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SLEEP_IN_BED = id("vanilla/adventure/sleep_in_bed");
    public static final ResourceKey<APLocation> VANILLA_END_DRAGON_BREATH = id("vanilla/end/dragon_breath");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_ROOT = id("vanilla/adventure/root");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_KILL_ALL_MOBS = id("vanilla/adventure/kill_all_mobs");
    public static final ResourceKey<APLocation> VANILLA_STORY_ENCHANT_ITEM = id("vanilla/story/enchant_item");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_VOLUNTARY_EXILE = id("vanilla/adventure/voluntary_exile");
    public static final ResourceKey<APLocation> VANILLA_STORY_FOLLOW_ENDER_EYE = id("vanilla/story/follow_ender_eye");
    public static final ResourceKey<APLocation> VANILLA_END_ROOT = id("vanilla/end/root");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_OBTAIN_NETHERITE_HOE = id("vanilla/husbandry/obtain_netherite_hoe");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_TOTEM_OF_UNDYING = id("vanilla/adventure/totem_of_undying");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_KILL_A_MOB = id("vanilla/adventure/kill_a_mob");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_ADVENTURING_TIME = id("vanilla/adventure/adventuring_time");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_PLANT_SEED = id("vanilla/husbandry/plant_seed");
    public static final ResourceKey<APLocation> VANILLA_NETHER_FIND_BASTION = id("vanilla/nether/find_bastion");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_HERO_OF_THE_VILLAGE = id("vanilla/adventure/hero_of_the_village");
    public static final ResourceKey<APLocation> VANILLA_NETHER_OBTAIN_ANCIENT_DEBRIS = id("vanilla/nether/obtain_ancient_debris");
    public static final ResourceKey<APLocation> VANILLA_NETHER_CREATE_FULL_BEACON = id("vanilla/nether/create_full_beacon");
    public static final ResourceKey<APLocation> VANILLA_NETHER_SUMMON_WITHER = id("vanilla/nether/summon_wither");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_BALANCED_DIET = id("vanilla/husbandry/balanced_diet");
    public static final ResourceKey<APLocation> VANILLA_NETHER_FAST_TRAVEL = id("vanilla/nether/fast_travel");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_ROOT = id("vanilla/husbandry/root");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_USE_LODESTONE = id("vanilla/adventure/use_lodestone");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_SAFELY_HARVEST_HONEY = id("vanilla/husbandry/safely_harvest_honey");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_TRADE = id("vanilla/adventure/trade");
    public static final ResourceKey<APLocation> VANILLA_NETHER_UNEASY_ALLIANCE = id("vanilla/nether/uneasy_alliance");
    public static final ResourceKey<APLocation> VANILLA_STORY_MINE_DIAMOND = id("vanilla/story/mine_diamond");
    public static final ResourceKey<APLocation> VANILLA_NETHER_FIND_FORTRESS = id("vanilla/nether/find_fortress");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_THROW_TRIDENT = id("vanilla/adventure/throw_trident");
    public static final ResourceKey<APLocation> VANILLA_STORY_ROOT = id("vanilla/story/root");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_HONEY_BLOCK_SLIDE = id("vanilla/adventure/honey_block_slide");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_OL_BETSY = id("vanilla/adventure/ol_betsy");
    public static final ResourceKey<APLocation> VANILLA_NETHER_NETHERITE_ARMOR = id("vanilla/nether/netherite_armor");
    public static final ResourceKey<APLocation> VANILLA_STORY_ENTER_THE_END = id("vanilla/story/enter_the_end");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_BREED_AN_ANIMAL = id("vanilla/husbandry/breed_an_animal");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_COMPLETE_CATALOGUE = id("vanilla/husbandry/complete_catalogue");
    public static final ResourceKey<APLocation> ARCHIPELAGO_GET_WOOD = id("archipelago/get_wood");
    public static final ResourceKey<APLocation> ARCHIPELAGO_GET_PICKAXE = id("archipelago/get_pickaxe");
    public static final ResourceKey<APLocation> ARCHIPELAGO_HOT_TOPIC = id("archipelago/hot_topic");
    public static final ResourceKey<APLocation> ARCHIPELAGO_BAKE_BREAD = id("archipelago/bake_bread");
    public static final ResourceKey<APLocation> ARCHIPELAGO_THE_LIE = id("archipelago/the_lie");
    public static final ResourceKey<APLocation> ARCHIPELAGO_RIDE_MINECART = id("archipelago/ride_minecart");
    public static final ResourceKey<APLocation> ARCHIPELAGO_CRAFT_SWORD = id("archipelago/craft_sword");
    public static final ResourceKey<APLocation> ARCHIPELAGO_COW_TIPPER = id("archipelago/cow_tipper");
    public static final ResourceKey<APLocation> ARCHIPELAGO_RIDE_PIG = id("archipelago/ride_pig");
    public static final ResourceKey<APLocation> ARCHIPELAGO_OVERKILL = id("archipelago/overkill");
    public static final ResourceKey<APLocation> ARCHIPELAGO_OBTAIN_BOOKSHELF = id("archipelago/obtain_bookshelf");
    public static final ResourceKey<APLocation> ARCHIPELAGO_OVERPOWERED = id("archipelago/overpowered");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_WAX_ON = id("vanilla/husbandry/wax_on");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_WAX_OFF = id("vanilla/husbandry/wax_off");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_AXOLOTL_IN_A_BUCKET = id("vanilla/husbandry/axolotl_in_a_bucket");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_KILL_AXOLOTL_TARGET = id("vanilla/husbandry/kill_axolotl_target");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SPYGLASS_AT_PARROT = id("vanilla/adventure/spyglass_at_parrot");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SPYGLASS_AT_GHAST = id("vanilla/adventure/spyglass_at_ghast");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_SPYGLASS_AT_DRAGON = id("vanilla/adventure/spyglass_at_dragon");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_LIGHTNING_ROD_WITH_VILLAGER_NO_FIRE = id("vanilla/adventure/lightning_rod_with_villager_no_fire");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_WALK_ON_POWDER_SNOW_WITH_LEATHER_BOOTS = id("vanilla/adventure/walk_on_powder_snow_with_leather_boots");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_MAKE_A_SIGN_GLOW = id("vanilla/husbandry/make_a_sign_glow");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_RIDE_A_BOAT_WITH_A_GOAT = id("vanilla/husbandry/ride_a_boat_with_a_goat");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_FALL_FROM_WORLD_HEIGHT = id("vanilla/adventure/fall_from_world_height");
    public static final ResourceKey<APLocation> VANILLA_NETHER_RIDE_STRIDER_IN_OVERWORLD_LAVA = id("vanilla/nether/ride_strider_in_overworld_lava");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_PLAY_JUKEBOX_IN_MEADOWS = id("vanilla/adventure/play_jukebox_in_meadows");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_TRADE_AT_WORLD_HEIGHT = id("vanilla/adventure/trade_at_world_height");
    // 1.19 advancements
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_ALLAY_DELIVER_CAKE_TO_NOTE_BLOCK = id("vanilla/husbandry/allay_deliver_cake_to_note_block");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_TADPOLE_IN_A_BUCKET = id("vanilla/husbandry/tadpole_in_a_bucket");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_KILL_MOB_NEAR_SCULK_CATALYST = id("vanilla/adventure/kill_mob_near_sculk_catalyst");
    public static final ResourceKey<APLocation> VANILLA_ADVENTURE_AVOID_VIBRATION = id("vanilla/adventure/avoid_vibration");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_LEASH_ALL_FROG_VARIANTS = id("vanilla/husbandry/leash_all_frog_variants");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_FROGLIGHTS = id("vanilla/husbandry/froglights");
    public static final ResourceKey<APLocation> VANILLA_HUSBANDRY_ALLAY_DELIVER_ITEM_TO_PLAYER = id("vanilla/husbandry/allay_deliver_item_to_player");
    
    private static ResourceKey<APLocation> id(String name) {
        return ResourceKey.create(APRegistries.ARCHIPELAGO_LOCATION, ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, name));
    }

    public static void bootstrap(BootstrapContext<APLocation> context) {
        context.register(VANILLA_NETHER_OBTAIN_CRYING_OBSIDIAN, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/obtain_crying_obsidian")));
        context.register(VANILLA_NETHER_DISTRACT_PIGLIN, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/distract_piglin")));
        context.register(VANILLA_STORY_OBTAIN_ARMOR, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/obtain_armor")));
        context.register(VANILLA_ADVENTURE_VERY_VERY_FRIGHTENING, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/very_very_frightening")));
        context.register(VANILLA_STORY_LAVA_BUCKET, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/lava_bucket")));
        context.register(VANILLA_END_KILL_DRAGON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/kill_dragon")));
        context.register(VANILLA_NETHER_ALL_POTIONS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/all_potions")));
        context.register(VANILLA_HUSBANDRY_TAME_AN_ANIMAL, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/tame_an_animal")));
        context.register(VANILLA_NETHER_CREATE_BEACON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/create_beacon")));
        context.register(VANILLA_STORY_DEFLECT_ARROW, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/deflect_arrow")));
        context.register(VANILLA_STORY_IRON_TOOLS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/iron_tools")));
        context.register(VANILLA_NETHER_BREW_POTION, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/brew_potion")));
        context.register(VANILLA_END_DRAGON_EGG, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/dragon_egg")));
        context.register(VANILLA_HUSBANDRY_FISHY_BUSINESS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/fishy_business")));
        context.register(VANILLA_NETHER_EXPLORE_NETHER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/explore_nether")));
        context.register(VANILLA_NETHER_RIDE_STRIDER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/ride_strider")));
        context.register(VANILLA_ADVENTURE_SNIPER_DUEL, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/sniper_duel")));
        context.register(VANILLA_NETHER_ROOT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/root")));
        context.register(VANILLA_END_LEVITATE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/levitate")));
        context.register(VANILLA_NETHER_ALL_EFFECTS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/all_effects")));
        context.register(VANILLA_ADVENTURE_BULLSEYE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/bullseye")));
        context.register(VANILLA_NETHER_GET_WITHER_SKULL, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/get_wither_skull")));
        context.register(VANILLA_HUSBANDRY_BRED_ALL_ANIMALS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/bred_all_animals")));
        context.register(VANILLA_STORY_MINE_STONE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/mine_stone")));
        context.register(VANILLA_ADVENTURE_TWO_BIRDS_ONE_ARROW, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/two_birds_one_arrow")));
        context.register(VANILLA_STORY_ENTER_THE_NETHER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/enter_the_nether")));
        context.register(VANILLA_ADVENTURE_WHOS_THE_PILLAGER_NOW, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/whos_the_pillager_now")));
        context.register(VANILLA_STORY_UPGRADE_TOOLS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/upgrade_tools")));
        context.register(VANILLA_HUSBANDRY_TACTICAL_FISHING, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/tactical_fishing")));
        context.register(VANILLA_STORY_CURE_ZOMBIE_VILLAGER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/cure_zombie_villager")));
        context.register(VANILLA_END_FIND_END_CITY, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/find_end_city")));
        context.register(VANILLA_STORY_FORM_OBSIDIAN, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/form_obsidian")));
        context.register(VANILLA_END_ENTER_END_GATEWAY, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/enter_end_gateway")));
        context.register(VANILLA_NETHER_OBTAIN_BLAZE_ROD, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/obtain_blaze_rod")));
        context.register(VANILLA_NETHER_LOOT_BASTION, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/loot_bastion")));
        context.register(VANILLA_ADVENTURE_SHOOT_ARROW, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/shoot_arrow")));
        context.register(VANILLA_HUSBANDRY_SILK_TOUCH_NEST, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/silk_touch_nest")));
        context.register(VANILLA_ADVENTURE_ARBALISTIC, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/arbalistic")));
        context.register(VANILLA_END_RESPAWN_DRAGON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/respawn_dragon")));
        context.register(VANILLA_STORY_SMELT_IRON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/smelt_iron")));
        context.register(VANILLA_NETHER_CHARGE_RESPAWN_ANCHOR, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/charge_respawn_anchor")));
        context.register(VANILLA_STORY_SHINY_GEAR, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/shiny_gear")));
        context.register(VANILLA_END_ELYTRA, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/elytra")));
        context.register(VANILLA_ADVENTURE_SUMMON_IRON_GOLEM, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/summon_iron_golem")));
        context.register(VANILLA_NETHER_RETURN_TO_SENDER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/return_to_sender")));
        context.register(VANILLA_ADVENTURE_SLEEP_IN_BED, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/sleep_in_bed")));
        context.register(VANILLA_END_DRAGON_BREATH, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/dragon_breath")));
        context.register(VANILLA_ADVENTURE_ROOT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/root")));
        context.register(VANILLA_ADVENTURE_KILL_ALL_MOBS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/kill_all_mobs")));
        context.register(VANILLA_STORY_ENCHANT_ITEM, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/enchant_item")));
        context.register(VANILLA_ADVENTURE_VOLUNTARY_EXILE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/voluntary_exile")));
        context.register(VANILLA_STORY_FOLLOW_ENDER_EYE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/follow_ender_eye")));
        context.register(VANILLA_END_ROOT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("end/root")));
        context.register(VANILLA_HUSBANDRY_OBTAIN_NETHERITE_HOE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/obtain_netherite_hoe")));
        context.register(VANILLA_ADVENTURE_TOTEM_OF_UNDYING, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/totem_of_undying")));
        context.register(VANILLA_ADVENTURE_KILL_A_MOB, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/kill_a_mob")));
        context.register(VANILLA_ADVENTURE_ADVENTURING_TIME, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/adventuring_time")));
        context.register(VANILLA_HUSBANDRY_PLANT_SEED, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/plant_seed")));
        context.register(VANILLA_NETHER_FIND_BASTION, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/find_bastion")));
        context.register(VANILLA_ADVENTURE_HERO_OF_THE_VILLAGE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/hero_of_the_village")));
        context.register(VANILLA_NETHER_OBTAIN_ANCIENT_DEBRIS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/obtain_ancient_debris")));
        context.register(VANILLA_NETHER_CREATE_FULL_BEACON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/create_full_beacon")));
        context.register(VANILLA_NETHER_SUMMON_WITHER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/summon_wither")));
        context.register(VANILLA_HUSBANDRY_BALANCED_DIET, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/balanced_diet")));
        context.register(VANILLA_NETHER_FAST_TRAVEL, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/fast_travel")));
        context.register(VANILLA_HUSBANDRY_ROOT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/root")));
        context.register(VANILLA_ADVENTURE_USE_LODESTONE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/use_lodestone")));
        context.register(VANILLA_HUSBANDRY_SAFELY_HARVEST_HONEY, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/safely_harvest_honey")));
        context.register(VANILLA_ADVENTURE_TRADE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/trade")));
        context.register(VANILLA_NETHER_UNEASY_ALLIANCE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/uneasy_alliance")));
        context.register(VANILLA_STORY_MINE_DIAMOND, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/mine_diamond")));
        context.register(VANILLA_NETHER_FIND_FORTRESS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/find_fortress")));
        context.register(VANILLA_ADVENTURE_THROW_TRIDENT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/throw_trident")));
        context.register(VANILLA_STORY_ROOT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/root")));
        context.register(VANILLA_ADVENTURE_HONEY_BLOCK_SLIDE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/honey_block_slide")));
        context.register(VANILLA_ADVENTURE_OL_BETSY, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/ol_betsy")));
        context.register(VANILLA_NETHER_NETHERITE_ARMOR, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/netherite_armor")));
        context.register(VANILLA_STORY_ENTER_THE_END, new AdvancementLocation(ResourceLocation.withDefaultNamespace("story/enter_the_end")));
        context.register(VANILLA_HUSBANDRY_BREED_AN_ANIMAL, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/breed_an_animal")));
        context.register(VANILLA_HUSBANDRY_COMPLETE_CATALOGUE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/complete_catalogue")));
        context.register(ARCHIPELAGO_GET_WOOD, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/get_wood")));
        context.register(ARCHIPELAGO_GET_PICKAXE, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/get_pickaxe")));
        context.register(ARCHIPELAGO_HOT_TOPIC, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/hot_topic")));
        context.register(ARCHIPELAGO_BAKE_BREAD, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/bake_bread")));
        context.register(ARCHIPELAGO_THE_LIE, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/the_lie")));
        context.register(ARCHIPELAGO_RIDE_MINECART, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/ride_minecart")));
        context.register(ARCHIPELAGO_CRAFT_SWORD, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/craft_sword")));
        context.register(ARCHIPELAGO_COW_TIPPER, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/cow_tipper")));
        context.register(ARCHIPELAGO_RIDE_PIG, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/ride_pig")));
        context.register(ARCHIPELAGO_OVERKILL, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/overkill")));
        context.register(ARCHIPELAGO_OBTAIN_BOOKSHELF, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/obtain_bookshelf")));
        context.register(ARCHIPELAGO_OVERPOWERED, new AdvancementLocation(ResourceLocation.fromNamespaceAndPath(APRandomizer.MODID, "archipelago/overpowered")));
        context.register(VANILLA_HUSBANDRY_WAX_ON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/wax_on")));
        context.register(VANILLA_HUSBANDRY_WAX_OFF, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/wax_off")));
        context.register(VANILLA_HUSBANDRY_AXOLOTL_IN_A_BUCKET, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/axolotl_in_a_bucket")));
        context.register(VANILLA_HUSBANDRY_KILL_AXOLOTL_TARGET, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/kill_axolotl_target")));
        context.register(VANILLA_ADVENTURE_SPYGLASS_AT_PARROT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/spyglass_at_parrot")));
        context.register(VANILLA_ADVENTURE_SPYGLASS_AT_GHAST, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/spyglass_at_ghast")));
        context.register(VANILLA_ADVENTURE_SPYGLASS_AT_DRAGON, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/spyglass_at_dragon")));
        context.register(VANILLA_ADVENTURE_LIGHTNING_ROD_WITH_VILLAGER_NO_FIRE, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/lightning_rod_with_villager_no_fire")));
        context.register(VANILLA_ADVENTURE_WALK_ON_POWDER_SNOW_WITH_LEATHER_BOOTS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/walk_on_powder_snow_with_leather_boots")));
        context.register(VANILLA_HUSBANDRY_MAKE_A_SIGN_GLOW, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/make_a_sign_glow")));
        context.register(VANILLA_HUSBANDRY_RIDE_A_BOAT_WITH_A_GOAT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/ride_a_boat_with_a_goat")));
        context.register(VANILLA_ADVENTURE_FALL_FROM_WORLD_HEIGHT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/fall_from_world_height")));
        context.register(VANILLA_NETHER_RIDE_STRIDER_IN_OVERWORLD_LAVA, new AdvancementLocation(ResourceLocation.withDefaultNamespace("nether/ride_strider_in_overworld_lava")));
        context.register(VANILLA_ADVENTURE_PLAY_JUKEBOX_IN_MEADOWS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/play_jukebox_in_meadows")));
        context.register(VANILLA_ADVENTURE_TRADE_AT_WORLD_HEIGHT, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/trade_at_world_height")));
        // 1.19 advancements
        context.register(VANILLA_HUSBANDRY_ALLAY_DELIVER_CAKE_TO_NOTE_BLOCK, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/allay_deliver_cake_to_note_block")));
        context.register(VANILLA_HUSBANDRY_TADPOLE_IN_A_BUCKET, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/tadpole_in_a_bucket")));
        context.register(VANILLA_ADVENTURE_KILL_MOB_NEAR_SCULK_CATALYST, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/kill_mob_near_sculk_catalyst")));
        context.register(VANILLA_ADVENTURE_AVOID_VIBRATION, new AdvancementLocation(ResourceLocation.withDefaultNamespace("adventure/avoid_vibration")));
        context.register(VANILLA_HUSBANDRY_LEASH_ALL_FROG_VARIANTS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/leash_all_frog_variants")));
        context.register(VANILLA_HUSBANDRY_FROGLIGHTS, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/froglights")));
        context.register(VANILLA_HUSBANDRY_ALLAY_DELIVER_ITEM_TO_PLAYER, new AdvancementLocation(ResourceLocation.withDefaultNamespace("husbandry/allay_deliver_item_to_player")));
    }
}
